# Generated by Django 3.2.16 on 2022-10-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Название города', max_length=50, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название Бригады', max_length=50, verbose_name='Бригада')),
                ('head', models.CharField(help_text='ФИО начальника', max_length=100, verbose_name='Начальник')),
                ('amount_people', models.IntegerField()),
                ('qualification', models.IntegerField()),
                ('city', models.ForeignKey(help_text='Опеределите группу', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='objects.city', verbose_name='Город')),
            ],
        ),
    ]
