# Generated by Django 3.2.16 on 2022-10-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20221019_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigada',
            name='city',
            field=models.ForeignKey(help_text='Определите город', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='objects.city', verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название объкта', max_length=50, verbose_name='Объект')),
                ('description', models.TextField(help_text='Описание работ на объекте', max_length=100, verbose_name='Описание работ')),
                ('brigada', models.ForeignKey(help_text='Определите бригаду', on_delete=django.db.models.deletion.CASCADE, related_name='brigada', to='objects.brigada', verbose_name='бригада')),
            ],
        ),
    ]
